#!/bin/bash
# Commands to run in your SSH session on the Linux VM
# Copy and paste these commands one by one into your Linux VM terminal

echo "🚀 Linux VM Setup and Training Commands"
echo "========================================"
echo ""
echo "Run these commands in your SSH session on the Linux VM:"
echo ""
echo "1️⃣  Navigate to project directory:"
echo "   cd ~/linux_security_agent"
echo ""
echo "2️⃣  Create virtual environment (if not exists):"
echo "   python3 -m venv venv"
echo ""
echo "3️⃣  Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "4️⃣  Install Python dependencies:"
echo "   pip install --upgrade pip"
echo "   pip install numpy pandas scikit-learn psutil rich click requests"
echo ""
echo "5️⃣  Install BCC tools for eBPF (optional but recommended):"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y bpfcc-tools python3-bpfcc linux-headers-\$(uname -r)"
echo ""
echo "6️⃣  Train models with REAL syscall data:"
echo "   sudo python3 core/enhanced_security_agent.py --train-models"
echo ""
echo "   💡 Tip: While training (60 seconds), generate activity in another terminal:"
echo "      ls -R /"
echo "      ps aux"
echo "      cat /etc/passwd"
echo ""
echo "7️⃣  Verify models were created:"
echo "   ls -lh ~/.cache/security_agent/"
echo ""
echo "8️⃣  Run the agent with dashboard:"
echo "   sudo python3 core/enhanced_security_agent.py --dashboard"
echo ""

