#!/bin/bash
# Setup training with external dataset and incremental learning

echo "🧠 ML Training Setup Guide"
echo "=========================="
echo ""

echo "📚 Option 1: Train with External Dataset"
echo "----------------------------------------"
echo ""
echo "1. Download or create a dataset (JSON format):"
echo "   See examples/dataset_example.json for format"
echo ""
echo "2. Train models:"
echo "   python3 scripts/train_with_dataset.py --file dataset.json"
echo ""
echo "3. Or from URL:"
echo "   python3 scripts/train_with_dataset.py --url https://example.com/dataset.json"
echo ""
echo "4. Or from directory:"
echo "   python3 scripts/train_with_dataset.py --directory ./datasets/"
echo ""

echo "🔄 Option 2: Train on Real System Data"
echo "--------------------------------------"
echo ""
echo "1. Collect real syscalls (60 seconds):"
echo "   python3 core/enhanced_security_agent.py --train-models"
echo ""
echo "2. Models saved to: ~/.cache/security_agent/"
echo ""

echo "📈 Option 3: Incremental Learning (Automatic)"
echo "----------------------------------------------"
echo ""
echo "1. Start monitoring with incremental retraining:"
echo "   python3 core/enhanced_security_agent.py --dashboard"
echo ""
echo "2. The system will:"
echo "   - Collect samples during monitoring"
echo "   - Auto-retrain every hour (if 100+ new samples)"
echo "   - Append new data to existing feature store"
echo "   - Keep last 200K samples"
echo ""

echo "✅ All options support --append to add to existing models"
echo ""

